package thoren.api.core;

import java.util.List;

import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import com.google.common.collect.Lists;

/**
 * @author ThorenDragonGem
 */
public class ThorInfo
{
	public static final String ID = "thorcore";
	public static final String NAME = "Thoren's Core API";
	public static final String VERSION = "a1.0.0";
	public static final String DESCRIPTION = "An API for many mods, such as Geologica, POTF or Civilisation mods.";
	public static final String CREDITS = "Created by ThorenDragonGem. Thanks to AlXndrTheGr8st for some classes.";
	public static final List<String> AUTHORS  = Lists.newArrayList("ThorenDragonGem");
	public static final String LOGO = "/assets/ThorCore/textures/logo/ThorCore.png";
	public static final String URL = "http://www.mediafire.com/download/3bmgtyvjc3bk3bk/ThorCore_API-a1.0.0.jar";
	public static final String CHANGELOGURL = "http://www.mediafire.com/download/o688wwri8t4pw6j/Changelog-ThorCore_API-a1.0.0.html";
	
	public static void setModInfoProperties(FMLPreInitializationEvent e)
	{
		e.getModMetadata().autogenerated = true;
		e.getModMetadata().modId = ID;
		e.getModMetadata().name = NAME;
		e.getModMetadata().version = VERSION;
		e.getModMetadata().description = DESCRIPTION;
		e.getModMetadata().credits = CREDITS;
		e.getModMetadata().authorList = AUTHORS;
		e.getModMetadata().logoFile = LOGO;
		e.getModMetadata().url = URL;
		e.getModMetadata().useDependencyInformation = true;
	}
}
